name: test_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BlackItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-BoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLight.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ExtraLightItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Light.ttf
        - asset: assets/fonts/Urbanist/Urbanist-LightItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-MediumItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBold.ttf
        - asset: assets/fonts/Urbanist/Urbanist-SemiBoldItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Thin.ttf
        - asset: assets/fonts/Urbanist/Urbanist-ThinItalic.ttf
        - asset: assets/fonts/Urbanist/Urbanist-Italic.ttf
          style: italic